
object:
  enable: "${OBJECT_ENABLE}"
  apiURL: "${OBJECT_APIURL}"
  minio:
    bucket: "${MINIO_BUCKET}"
    endpoint: "${MINIO_ENDPOINT}"
    accessKeyID: "${MINIO_ACCESS_KEY}"
    secretAccessKey: "${MINIO_SECRET_KEY}"
    sessionToken: ""
  cos:
    bucketURL: "${COS_BUCKET_URL}"
    secretID: ""
    secretKey: ""
    sessionToken: ""
  oss:
    endpoint: "${OSS_ENDPOINT}"
    bucket: "${OSS_BUCKET}"
    bucketURL: "${OSS_BUCKET_URL}"
    accessKeyID: "${OSS_ACCESS_KEY_ID}"
    accessKeySecret: ""
    sessionToken: ""
