groupCreated:
  isSendMsg: true //是否发送消息，false不发消息为无声的触发同步。true发消息需要触发会话，rpc notification直接发两次，一次消息一次通知, options字段isNotification是否为通知
  reliabilityLevel: 1 // 1为online才发送 2为必达
  unreadCount: false // 只在isSendMsg为true的情况下有作用
  offlinePush:
    enable: false // 开启该开关
    title: "create group title" # xx create the group
    desc: "create group desc"
    ext: "create group ext"
  
# 不加消息contentType，content统一json 结构体使用pb的


groupInfoSet:
  isSendMsg: true
  unreadCount: false
  offlinePush:
    enable: false
    title: "groupInfoSet title"
    desc: "groupInfoSet desc"
    ext: "groupInfoSet ext"


joinGroupApplication:
  isSendMsg: true
  unreadCount: false
  offlinePush:
    enable: false
    title: "joinGroupApplication title"
    desc: "joinGroupApplication desc"
    ext: "joinGroupApplication ext"

memberQuit:
  isSendMsg: true
  unreadCount: false
  offlinePush:
    enable: false
    title: "memberQuit title"
    desc: "memberQuit desc"
    ext: "memberQuit ext"
 
groupApplicationAccepted:
  isSendMsg: true
  unreadCount: false
  offlinePush:
    enable: false
    title: "groupApplicationAccepted title"
    desc: "groupApplicationAccepted desc"
    ext: "groupApplicationAccepted ext"
 
groupApplicationRejected:
  isSendMsg: true
  unreadCount: false
  offlinePush:
    enable: false
    title: " title"
    desc: " desc"
    ext: " ext"


groupOwnerTransferred:
  isSendMsg: true
  unreadCount: false
  offlinePush:
    enable: false
    title: "groupOwnerTransferred title"
    desc: "groupOwnerTransferred desc"
    ext: "groupOwnerTransferred ext"

memberKicked:
  isSendMsg: true
  unreadCount: false
  offlinePush:
    enable: false
    title: "memberKicked title"
    desc: "memberKicked desc"
    ext: "memberKicked ext"

memberInvited:
  isSendMsg: true
  unreadCount: false
  offlinePush:
    enable: false
    title: "memberInvited title"
    desc: "memberInvited desc"
    ext: "memberInvited ext"

memberEnter:
  isSendMsg: true
  unreadCount: false
  offlinePush:
    enable: false
    title: "memberEnter title"
    desc: "memberEnter desc"
    ext: "memberEnter ext"

groupDismissed:
  isSendMsg: true
  unreadCount: false
  offlinePush:
    enable: false
    title: "groupDismissed title"
    desc: "groupDismissed desc"
    ext: "groupDismissed ext"

groupMuted:
  isSendMsg: true
  unreadCount: false
  offlinePush:
    enable: false
    title: "groupMuted title"
    desc: "groupMuted desc"
    ext: "groupMuted ext"

groupCancelMuted:
  isSendMsg: true
  unreadCount: false
  offlinePush:
    enable: false
    title: "groupCancelMuted title"
    desc: "groupCancelMuted desc"
    ext: "groupCancelMuted ext"
  defaultTips:
    tips: "group Cancel Muted"


groupMemberMuted:
  isSendMsg: true
  unreadCount: false
  offlinePush:
    enable: false
    title: "groupMemberMuted title"
    desc: "groupMemberMuted desc"
    ext: "groupMemberMuted ext"

groupMemberCancelMuted:
  isSendMsg: true
  unreadCount: false
  offlinePush:
    enable: false
    title: "groupMemberCancelMuted title"
    desc: "groupMemberCancelMuted desc"
    ext: "groupMemberCancelMuted ext"

groupMemberInfoSet:
  isSendMsg: true
  unreadCount: false
  offlinePush:
    enable: false
    title: "groupMemberInfoSet title"
    desc: "groupMemberInfoSet desc"
    ext: "groupMemberInfoSet ext"

#############################friend#################################
friendApplicationAdded:
  isSendMsg: true
  unreadCount: false 
  offlinePush:
    enable: false
    title: "Somebody applies to add you as a friend"
    desc: "Somebody applies to add you as a friend"
    ext: "Somebody applies to add you as a friend"

friendApplicationApproved:
  isSendMsg: true
  unreadCount: false 
  offlinePush:
    enable: true
    title: "Someone applies to add your friend application"
    desc: "Someone applies to add your friend application"
    ext: "Someone applies to add your friend application"

friendApplicationRejected:
  isSendMsg: true
  unreadCount: false 
  offlinePush:
    enable: true
    title: "Someone rejected your friend application"
    desc: "Someone rejected your friend application"
    ext: "Someone rejected your friend application"

friendAdded:
  isSendMsg: true
  unreadCount: false 
  offlinePush:
    enable: true
    title: "We have become friends"
    desc: "We have become friends"
    ext: "We have become friends"

friendDeleted:
  isSendMsg: true
  unreadCount: false 
  offlinePush:
    enable: true
    title: "deleted a friend"
    desc: "deleted a friend"
    ext: "deleted a friend"

friendRemarkSet:
  isSendMsg: true
  unreadCount: false 
  offlinePush:
    enable: true
    title: "Your friend's profile has been changed"
    desc: "Your friend's profile has been changed"
    ext: "Your friend's profile has been changed"

blackAdded:
  isSendMsg: true
  unreadCount: false 
  offlinePush:
    enable: true
    title: "blocked a user"
    desc: "blocked a user"
    ext: "blocked a user"

blackDeleted:
  isSendMsg: true
  unreadCount: false 
  offlinePush:
    enable: true
    title: "Remove a blocked user"
    desc: "Remove a blocked user"
    ext: "Remove a blocked user"

friendInfoUpdated:
  isSendMsg: true
  unreadCount: false 
  offlinePush:
    enable: true
    title: "friend info updated"
    desc: "friend info updated"
    ext: "friend info updated"

#####################user#########################
userInfoUpdated:
  isSendMsg: true
  unreadCount: false 
  offlinePush:
    enable: true
    title: "Remove a blocked user"
    desc: "Remove a blocked user"
    ext: "Remove a blocked user"

#####################conversation#########################
conversationOptUpdate:
  isSendMsg: true
  unreadCount: false 
  offlinePush:
    enable: true
    title: "conversation opt update"
    desc: "conversation opt update"
    ext: "conversation opt update"

conversationSetPrivate:
  isSendMsg: true
  unreadCount: false 
  offlinePush:
    enable: true
    title: "burn after reading"
    desc: "burn after reading"
    ext: "burn after reading"

